<a href="https://colab.research.google.com/github/HarishMayakuntla/Data-science-pandas-practice/blob/main/02_pd_Selecting_Filtering_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selecting, Filtering, Sorting

## Create a DataFrame

In [1]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Priya", "Anil", "Sneha"],
    "Age": [22, 25, 21, 24, 23],
    "Marks": [85, 72, 91, 65, 78],
    "City": ["Kadiri", "Hyderabad", "Bangalore", "Kadiri", "Chennai"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
1   Rahul   25     72  Hyderabad
2   Priya   21     91  Bangalore
3    Anil   24     65     Kadiri
4   Sneha   23     78    Chennai

# selecting Data

Selecting means getting particular columns or rows from a DataFrame

###  Select single column

* Syntax :
     
      df['column']

In [2]:
## select one column

df['Name']

0    Harish
1     Rahul
2     Priya
3      Anil
4     Sneha
Name: Name, dtype: object

### Select multiple columns

   * Syntax :
     
      df [['column','column']]

In [3]:

## slecting multiple columns

df[['Name','Age']] # multiple column

     Name  Age
0  Harish   22
1   Rahul   25
2   Priya   21
3    Anil   24
4   Sneha   23

###  Selecting Rows — iloc

iloc means select using integer position

In [ ]:
df.iloc[0:3,0:3]

     Name  Age  Marks
0  Harish   22     85
1   Rahul   25     72
2   Priya   21     91

In [ ]:
df.iloc[2]

Name         Priya
Age             21
Marks           91
City     Bangalore
Name: 2, dtype: object

In [ ]:
df.iloc[0,[1,2]]

Age      22
Marks    85
Name: 0, dtype: object

### Selecting Using -loc

loc selects using labels

it depends on integers

In [ ]:
df.loc[0]

Name     Harish
Age          22
Marks        85
City     Kadiri
Name: 0, dtype: object

In [ ]:
df.loc[0, "Name"]

'Harish'

In [ ]:
df.loc[0:2,['Name','Marks']]

     Name  Marks
0  Harish     85
1   Rahul     72
2   Priya     91

In [ ]:
df.index = ["A", "B", "C", "D",'E']
df

     Name  Age  Marks       City
A  Harish   22     85     Kadiri
B   Rahul   25     72  Hyderabad
C   Priya   21     91  Bangalore
D    Anil   24     65     Kadiri
E   Sneha   23     78    Chennai

In [ ]:
df.loc['B']

Name         Rahul
Age             25
Marks           72
City     Hyderabad
Name: B, dtype: object

### difference between iloc  vs loc

| Feature           | `loc`               | `iloc`                   |
| ----------------- | ------------------- | ------------------------ |
| Meaning           | Label location      | Integer location         |
| Uses              | Labels              | Positions                |
| Row               | `df.loc["A"]`       | `df.iloc[0]`             |
| Column            | `df.loc[:, "Name"]` | `df.iloc[:, 0]`          |
| Multiple rows     | `df.loc["A":"C"]`   | `df.iloc[0:3]`           |
| Slice ending      | Included            | Excluded                 |
| Boolean filtering |                     | Usually not the main use |

# Filtering

Filtering means getting rows that satisfy a condition

### Filtering with <,>

In [ ]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Priya", "Anil", "Sneha"],
    "Age": [22, 25, 21, 24, 23],
    "Marks": [85, 72, 91, 65, 78],
    "City": ["Kadiri", "Hyderabad", "Bangalore", "Kadiri", "Chennai"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
1   Rahul   25     72  Hyderabad
2   Priya   21     91  Bangalore
3    Anil   24     65     Kadiri
4   Sneha   23     78    Chennai

In [ ]:
## i need check whose marks grater than 80

df[df['Marks']>80]

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
2   Priya   21     91  Bangalore

In [ ]:
df['Marks']>80  # here the otput as boolean type

0     True
1    False
2     True
3    False
4    False
Name: Marks, dtype: bool

In [ ]:
## i check age less than 21

df[df['Age']<22]

    Name  Age  Marks       City
2  Priya   21     91  Bangalore

### Filter with == , <= ,>= ,!=

In [ ]:
df[df['City']=='Kadiri']

     Name  Age  Marks    City
0  Harish   22     85  Kadiri
3    Anil   24     65  Kadiri

In [ ]:
df[df['Age']<=22]

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
2   Priya   21     91  Bangalore

In [ ]:
df[df['Marks']>=65]

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
1   Rahul   25     72  Hyderabad
2   Priya   21     91  Bangalore
3    Anil   24     65     Kadiri
4   Sneha   23     78    Chennai

In [ ]:
df[df['Name']!='Harish']

    Name  Age  Marks       City
1  Rahul   25     72  Hyderabad
2  Priya   21     91  Bangalore
3   Anil   24     65     Kadiri
4  Sneha   23     78    Chennai

### Multiple Comditions

AND ----- >  &

OR ------->  |

In [ ]:
## we need check mutiple conditions at single time
## if the both condition must be true

df[(df['Marks']<85)&(df['Age']>23)]

    Name  Age  Marks       City
1  Rahul   25     72  Hyderabad
3   Anil   24     65     Kadiri

In [ ]:
## in OR if only on condition is True
# it will give both condtion satisfys

df[(df['Marks']<85)|(df['Age']>23)]

    Name  Age  Marks       City
1  Rahul   25     72  Hyderabad
3   Anil   24     65     Kadiri
4  Sneha   23     78    Chennai

### Filtering with isin()  , between ()

In [ ]:
## it better thanmultiple OR condtions

df[df["City"].isin(["Kadiri", "Chennai"])]

     Name  Age  Marks     City
0  Harish   22     85   Kadiri
3    Anil   24     65   Kadiri
4   Sneha   23     78  Chennai

In [ ]:
## check in between values

df[df["Marks"].between(70,85)]

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
1   Rahul   25     72  Hyderabad
4   Sneha   23     78    Chennai

# Sorting

Sorting means arranging your data

In [ ]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Priya", "Anil", "Sneha"],
    "Age": [22, 25, 21, 24, 23],
    "Marks": [85, 72, 91, 65, 78],
    "City": ["Kadiri", "Hyderabad", "Bangalore", "Kadiri", "Chennai"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
1   Rahul   25     72  Hyderabad
2   Priya   21     91  Bangalore
3    Anil   24     65     Kadiri
4   Sneha   23     78    Chennai

In [ ]:
df.sort_values('Marks')

     Name  Age  Marks       City
3    Anil   24     65     Kadiri
1   Rahul   25     72  Hyderabad
4   Sneha   23     78    Chennai
0  Harish   22     85     Kadiri
2   Priya   21     91  Bangalore

In [ ]:
df.sort_values('Marks',ascending=False)

     Name  Age  Marks       City
2   Priya   21     91  Bangalore
0  Harish   22     85     Kadiri
4   Sneha   23     78    Chennai
1   Rahul   25     72  Hyderabad
3    Anil   24     65     Kadiri

In [ ]:
df.sort_values(['City','Marks'])

     Name  Age  Marks       City
2   Priya   21     91  Bangalore
4   Sneha   23     78    Chennai
1   Rahul   25     72  Hyderabad
3    Anil   24     65     Kadiri
0  Harish   22     85     Kadiri

In [ ]:
df.sort_index(ascending=False)

     Name  Age  Marks       City
4   Sneha   23     78    Chennai
3    Anil   24     65     Kadiri
2   Priya   21     91  Bangalore
1   Rahul   25     72  Hyderabad
0  Harish   22     85     Kadiri

In [ ]:
df.sort_index()

     Name  Age  Marks       City
0  Harish   22     85     Kadiri
1   Rahul   25     72  Hyderabad
2   Priya   21     91  Bangalore
3    Anil   24     65     Kadiri
4   Sneha   23     78    Chennai

     Name  Age  Marks       City
2   Priya   21     91  Bangalore
0  Harish   22     85     Kadiri
4   Sneha   23     78    Chennai
3    Anil   24     65     Kadiri
1   Rahul   25     72  Hyderabad

In [ ]:
df[df["Marks"] > 75][["Name", "Marks"]].sort_values(
    "Marks",
    ascending=False
)

     Name  Marks
2   Priya     91
0  Harish     85
4   Sneha     78