<a href="https://colab.research.google.com/github/HarishMayakuntla/Data-science-pandas-practice/blob/main/07_Merge_Join_Concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pands using Merge, Join, Concat

## Merge

Use merge() when two DataFrames have a common column

* Syntax:

           pd.merge(left, right, on="column_name")

In [2]:
import pandas as pd

df1=pd.DataFrame({

        'ID':[1,2,3,4],
        'Name':['harish','ramesh','ganesh','mukesh']
})

In [3]:
df1

   ID    Name
0   1  harish
1   2  ramesh
2   3  ganesh
3   4  mukesh

In [11]:
df2=pd.DataFrame({

    "ID": [1,2,3,4],
    "Marks": [80,90,95,99]

})

In [12]:
df2

   ID  Marks
0   1     80
1   2     90
2   3     95
3   4     99

In [17]:
pd.merge(df1,df2) ## defaultly it take common row as reference

   ID    Name  Marks
0   1  Harish     85
1   2   Rahul     90
2   3    Ravi     95

### 1.Inner Merge (Default)

Returns only matching rows

In [19]:
df1 = pd.DataFrame({
    "ID": [1,2,3],
    "Name": ["A","B","C"]
})

df2 = pd.DataFrame({
    "ID": [2,3,4],
    "Marks": [80,90,95]
})

In [21]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [22]:
df2

   ID  Marks
0   2     80
1   3     90
2   4     95

In [20]:
pd.merge(df1, df2, on="ID", how="inner") # give common rows

   ID Name  Marks
0   2    B     80
1   3    C     90

### 2.Left Merge

Returns all rows from the left DataFrame

In [28]:
pd.merge(df1,df2,on='ID',how='left')

   ID Name  Marks
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0

### 3.Right Merge

Returns all rows from the right DataFrame

In [29]:
pd.merge(df1, df2, on="ID", how="right")

   ID Name  Marks
0   2    B     80
1   3    C     90
2   4  NaN     95

###4. Outer Merge

Returns all rows from both DataFrames.

In [30]:
pd.merge(df1, df2, on="ID", how="outer")

   ID Name  Marks
0   1    A    NaN
1   2    B   80.0
2   3    C   90.0
3   4  NaN   95.0

## join

Use join() when combining DataFrames based on their index

In [47]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Harish", "Rahul", "Ravi"]
})

df2 = pd.DataFrame({
    "Marks": [85,90,95]
})

In [48]:
df1

     Name
0  Harish
1   Rahul
2    Ravi

In [49]:
df2

   Marks
0     85
1     90
2     95

In [50]:
df1.join(df2)

     Name  Marks
0  Harish     85
1   Rahul     90
2    Ravi     95

## concat

Use concat() to stack DataFrames either vertically (rows) or horizontally (columns)

### vertical conactination

In [57]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Harish", "Rahul"]
},index=[1,2])

df2 = pd.DataFrame({
     "Marks": [85,90]
},index=[1,2])

In [58]:
pd.concat([df1, df2])

     Name  Marks
1  Harish    NaN
2   Rahul    NaN
1     NaN   85.0
2     NaN   90.0

### reset index

In [60]:
pd.concat([df1, df2], ignore_index=True)

     Name  Marks
0  Harish    NaN
1   Rahul    NaN
2     NaN   85.0
3     NaN   90.0

## horizontal concatination

In [61]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Harish", "Rahul"]
})

df2 = pd.DataFrame({
    "Marks": [85,90]
})

In [62]:
pd.concat([df1, df2], axis=1)

     Name  Marks
0  Harish     85
1   Rahul     90