<a href="https://colab.research.google.com/github/HarishMayakuntla/Data-science-pandas-practice/blob/main/08_Pivot_Tables_Crosstab_Datetime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas using Pivot Tables, Crosstab, Datetime

## Pivot Table


A Pivot Table is used to summarize data.

It can calculate:

* Sum
* Mean
* Count
* Max
* Min

Instead of manually filtering data, pivot_table() creates a summary table.

In [2]:
import pandas as pd

data = {
    "Department":["IT","HR","IT","HR","Sales","Sales"],
    "Employee":["A","B","C","D","E","F"],
    "Salary":[50000,40000,60000,45000,55000,52000]
}

df = pd.DataFrame(data)

df

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3         HR        D   45000
4      Sales        E   55000
5      Sales        F   52000

In [6]:
##  find mean

pd.pivot_table(
    df,
    values='Salary',
    index="Department",
    aggfunc='mean'


)

             Salary
Department
HR          42500.0
IT          55000.0
Sales       53500.0

In [23]:
# count of

pd.pivot_table(
    df,
    values='Salary',
    index="Department",
    aggfunc='count'
)

            Salary
Department
HR               2
IT               2
Sales            2

In [21]:
#find sum

pd.pivot_table(

      df,
      values='Salary',
      index='Department',
      aggfunc='sum'

)

            Salary
Department
HR           85000
IT          110000
Sales       107000

### Multiple Aggregations

In [25]:
pd.pivot_table(
    df,
    values='Salary',
    index='Department',
    aggfunc=['sum','mean','std','count','min','max']
)

               sum     mean          std  count    min    max
            Salary   Salary       Salary Salary Salary Salary
Department
HR           85000  42500.0  3535.533906      2  40000  45000
IT          110000  55000.0  7071.067812      2  50000  60000
Sales       107000  53500.0  2121.320344      2  52000  55000

### Two - leval pivot table

In [26]:
df['Gender']=['M','F','M','M','F','M']
df

  Department Employee  Salary Gender
0         IT        A   50000      M
1         HR        B   40000      F
2         IT        C   60000      M
3         HR        D   45000      M
4      Sales        E   55000      F
5      Sales        F   52000      M

In [27]:
pd.pivot_table(

        df,
        values='Salary',
        index='Employee',
        columns='Gender',
        aggfunc=['sum','mean','count']
)

              sum              mean          count
Gender          F        M        F        M     F    M
Employee
A             NaN  50000.0      NaN  50000.0   NaN  1.0
B         40000.0      NaN  40000.0      NaN   1.0  NaN
C             NaN  60000.0      NaN  60000.0   NaN  1.0
D             NaN  45000.0      NaN  45000.0   NaN  1.0
E         55000.0      NaN  55000.0      NaN   1.0  NaN
F             NaN  52000.0      NaN  52000.0   NaN  1.0

## missing values

In [30]:
pd.pivot_table(

        df,
        values='Salary',
        index='Employee',
        columns='Gender',
        aggfunc=['sum','mean','count'],
        fill_value=0
)

            sum            mean          count
Gender        F      M        F        M     F  M
Employee
A             0  50000      0.0  50000.0     0  1
B         40000      0  40000.0      0.0     1  0
C             0  60000      0.0  60000.0     0  1
D             0  45000      0.0  45000.0     0  1
E         55000      0  55000.0      0.0     1  0
F             0  52000      0.0  52000.0     0  1

# Crosstab

crosstab() counts how many times combinations of categories occur

In [31]:
df

  Department Employee  Salary Gender
0         IT        A   50000      M
1         HR        B   40000      F
2         IT        C   60000      M
3         HR        D   45000      M
4      Sales        E   55000      F
5      Sales        F   52000      M

In [35]:
pd.crosstab(
    df['Department'],
    df['Gender']
)

Gender      F  M
Department
HR          1  1
IT          0  2
Sales       1  1

Grand percentage

In [36]:
# it give  in percentage

pd.crosstab(
    df['Department'],
    df['Gender'],
    normalize=True
)

Gender             F         M
Department
HR          0.166667  0.166667
IT          0.000000  0.333333
Sales       0.166667  0.166667

### Add toatals

In [38]:
pd.crosstab(
    df['Department'],
    df['Gender'],
    margins=True
)

Gender      F  M  All
Department
HR          1  1    2
IT          0  2    2
Sales       1  1    2
All         2  4    6

###========================= pivot  vs  crosstab =================

| Pivot Table                         | Crosstab                       |
| ----------------------------------- | ------------------------------ |
| Summarizes values                   | Counts category combinations   |
| Uses numeric values                 | Uses categorical data          |
| Supports `sum`, `mean`, `max`, etc. | Mainly frequency counts        |
| Requires `values` and `aggfunc`     | Works directly with categories |

# Datetime

Almost every real-world dataset has dates

In [61]:
## covert string to Datatime

import pandas as pd

df = pd.DataFrame({

    "Date":["2026-08-01","2026-08-02","2026-08-03"]
})

df["Date"] = pd.to_datetime(df["Date"])

df

        Date
0 2026-08-01
1 2026-08-02
2 2026-08-03

In [45]:
df.dtypes

Date    datetime64[ns]
dtype: object

In [51]:
## extract Year
df['Year'] = df['Date'].dt.year
df['Year']

0    2026
1    2026
2    2026
Name: Year, dtype: int32

In [52]:
## extract month
df['Month'] = df['Date'].dt.month
df['Month']

0    8
1    8
2    8
Name: Month, dtype: int32

In [53]:
## extract day

df["Day"] = df["Date"].dt.day
df['Day']

0    1
1    2
2    3
Name: Day, dtype: int32

In [55]:
## day name
df["Date"].dt.day_name()

0    Saturday
1      Sunday
2      Monday
Name: Date, dtype: object

In [56]:
# month name
df["Date"].dt.month_name()

0    August
1    August
2    August
Name: Date, dtype: object

In [57]:
# weakday number
df["Date"].dt.weekday

0    5
1    6
2    0
Name: Date, dtype: int32

### Current Datatime

In [58]:
pd.Timestamp.now()

Timestamp('2026-08-01 13:01:08.945112')

## Date Difference

In [59]:
df = pd.DataFrame({
    "Start":["2026-08-01"],
    "End":["2026-08-10"]
})

df["Start"] = pd.to_datetime(df["Start"])
df["End"] = pd.to_datetime(df["End"])

df["Days"] = df["End"] - df["Start"]
df

       Start        End   Days
0 2026-08-01 2026-08-10 9 days

In [62]:
## sort by dates

df.sort_values("Date")

        Date
0 2026-08-01
1 2026-08-02
2 2026-08-03

In [63]:
# Filter by Date

df[df["Date"] > "2026-08-01"]

        Date
1 2026-08-02
2 2026-08-03