<a href="https://colab.research.google.com/github/HarishMayakuntla/Data-science-pandas-practice/blob/main/Pandas_intro_datastructures_create_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas



*   Pandas is a python library
*   which handles the dataframe like excel,csv,j.son  etc

## pandas handles

* Series, DataFrame, Creating Data
* Reading/Writing CSV, Excel, JSON
*	Selecting, Filtering, Sorting
* Missing Values, Duplicates
* String Operations, Apply, Map
*  GroupBy, Aggregation
*  Merge, Join, Concat
* Pivot Tables, Crosstab, Datetime

## Where is Pandas Used?

Pandas is widely used in:

* Data Analysis
* Data Science
* Machine Learning
* Artificial Intelligence
* Finance
* Banking
* Healthcare
* E-commerce
* Business Intelligence

## download libarary

In [ ]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## import the library

In [ ]:
import pandas as pd

In [ ]:
# check verstion

pd.__version__

'2.2.2'

## Data Structure in pandas

* series
* DataFrame

## What is a Series?

A Series is a one-dimensional data structure.
 * like list ,tuple ,set ,dict so we can use the single colume

 * series has only one dimenstion like the  1D array

* every value in series has index

 ### Syntax :

     pd.Series([elements])

In [ ]:
# series follwed by the index

price=pd.Series([20,50,60,40,80,900])
price

0     20
1     50
2     60
3     40
4     80
5    900
dtype: int64

In [ ]:
# here left side is index   0   1   2  3  4   5
# and right sside is values 20  50  60 40 80  900

In [ ]:
price[0]  # here index works

np.int64(20)

In [ ]:
price[4]

np.int64(80)

### create custom index

Instead of default indexes (0, 1, 2...), you can define your own

In [ ]:
marks=pd.Series(
    [50,80,60],

    index=['maths','Telugu','social']

)

marks

maths     50
Telugu    80
social    60
dtype: int64

In [ ]:
marks['maths']

np.int64(50)

### create series in dictionary

In [ ]:
student={
    'harish':70.0,
    'coures':'data science',
    'age':21,
    'fee':'none'
}

s=pd.Series(student)

s

harish            70.0
coures    data science
age                 21
fee               none
dtype: object

In [ ]:
s['harish']

70.0

### create Series in  differnt data type

In [ ]:
## NUMBERS
pd.Series([20,30,50,60,5])

0    20
1    30
2    50
3    60
4     5
dtype: int64

In [ ]:
## Strings
pd.Series(['mango','apple','orange'])

0     mango
1     apple
2    orange
dtype: object

In [ ]:
## boolean

pd.Series([True,False,True,False,True])

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
## float or decimals
pd.Series([2.5,6.25,600.865,873.5421])

0      2.5000
1      6.2500
2    600.8650
3    873.5421
dtype: float64

### Useful Series Attributes

In [ ]:

marks = pd.Series([80,90,70,95])

In [ ]:
# Length
len(marks)

4

In [ ]:
marks.shape  # no.of elements, no.of dimenstion

(4,)

In [ ]:
marks.dtype

dtype('int64')

In [ ]:
marks.values

array([80, 90, 70, 95])

In [ ]:
marks.index

RangeIndex(start=0, stop=4, step=1)

# What is a DataFrame?

A DataFrame is a two-dimensional table
* it is also follwed by index

### Syntax :

         pd.DataFrame(data)

### create the DataFrame

In [ ]:
data={

      'name':['harish','ramesh','somesh'],
      'age':[21,22,22],
      'course':['datascience','python fullstack','data analytics']
}

df=pd.DataFrame(data)

df

     name  age            course
0  harish   21       datascience
1  ramesh   22  python fullstack
2  somesh   22    data analytics

In [ ]:
## above   index 0 1 2 and it represents the rows
## and the name , age ,course are columes
## the remaing is the data

In [ ]:
print(df["name"])

0    harish
1    ramesh
2    somesh
Name: name, dtype: object

In [ ]:
df[['name','age','course']]

     name  age            course
0  harish   21       datascience
1  ramesh   22  python fullstack
2  somesh   22    data analytics

In [ ]:
df.ndim   ## dimenstons

2

In [ ]:
df.shape

(3, 3)

In [ ]:
df.columns

Index(['name', 'age', 'course'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.dtypes

name      object
age        int64
course    object
dtype: object

### From a List of Lists

In [ ]:
data = [
    ["Harish",22],
    ["Rahul",23],
    ["Ravi",21]
]

df = pd.DataFrame(data, columns=["Name","Age"])

df

     Name  Age
0  Harish   22
1   Rahul   23
2    Ravi   21

### From a List of Dictionaries

In [ ]:
data = [
    {"Name":"Harish","Age":22},
    {"Name":"Rahul","Age":23},
    {"Name":"Ravi","Age":21}
]

df=pd.DataFrame(data)

df

     Name  Age
0  Harish   22
1   Rahul   23
2    Ravi   21

## create  from using numpy array

In [ ]:
import numpy as np

In [ ]:
arr=np.random.randint(1,10,(3,3))
arr

array([[3, 3, 2],
       [4, 8, 4],
       [1, 4, 2]])

In [ ]:
df=pd.DataFrame(arr,columns=['A','B','C'])
df

   A  B  C
0  3  3  2
1  4  8  4
2  1  4  2

### ============= Series vs DataFarame =================

| Feature                    | Series        | DataFrame        |
| -------------------------- | ------------- | ---------------- |
| Dimensions                 | 1             | 2                |
| Looks like                 | One column    | Full table       |
| Created with               | `pd.Series()` | `pd.DataFrame()` |
| Example                    | Marks         | Student table    |
| Can have multiple columns? |  No          |  Yes            |