# Missing Values, Duplicates

## Missing Values

A missing value means some data is not available.

### example :

| Name   | Age | Salary |
| ------ | --: | -----: |
| Harish |  22 |  30000 |
| Rahul  | NaN |  40000 |
| Rohit  |  24 |    NaN |





NAN ---- > means not a number / missing value

In [71]:
## create a DataFrame

import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Rohit", "Anil"],
    "Age": [22, None, 24, None],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)

print(df)

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0      NaN
3    Anil   NaN  35000.0

## Finding missing values

### using isnull()  Or isna()

both are same

In [75]:
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

* True → missing value
* False → value exists

In [ ]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

## Count Missing Values

This is one of the most important commands
* counts no.of missing values

### using isnull().sum()

In [ ]:
df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

Meaning:

* m Name → 0 missing
* Age → 2 missing
* Salary → 1 missing

## Find Rows Having Missing Values

This gives rows where at least one value is missing

In [ ]:
df[df.isnull().any(axis=1)]

    Name   Age   Salary
1  Rahul   NaN  40000.0
2  Rohit  24.0      NaN
3   Anil   NaN  35000.0

## Find Columns Having Missing Values

In [ ]:
df.columns[df.isnull().any()]

Index(['Age', 'Salary'], dtype='object')

In [ ]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

# remove Missing Values

### use dropna()

* This removes rows containing missing values
* dropna() does not permanently change df by default

In [ ]:
df.dropna()

     Name   Age   Salary
0  Harish  22.0  30000.0

## Remove Rows Only When All Values Are Missing

In [ ]:
df.dropna(how='all')

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0      NaN
3    Anil   NaN  35000.0

## Remove Missing Values From a Specific Column

In [ ]:
df.dropna(subset=["Age"])  # Remove rowes where "Age" is missing

     Name   Age   Salary
0  Harish  22.0  30000.0
2   Rohit  24.0      NaN

## Fill Missing Values

* Instead of deleting data, sometimes we want to replace missing values

 ###  use fillna()  ----> fill null values

In [ ]:
df.fillna(0)
df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   0.0  40000.0
2   Rohit  24.0      0.0
3    Anil   0.0  35000.0

## perticular column

In [21]:

import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Rohit", "Anil"],
    "Age": [22, None, 24, None],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)

df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0      NaN
3    Anil   NaN  35000.0

In [22]:
df['Age']

0    22.0
1     NaN
2    24.0
3     NaN
Name: Age, dtype: float64

In [23]:
df["Age"]=df['Age'].fillna(0)

In [24]:
df['Age']

0    22.0
1     0.0
2    24.0
3     0.0
Name: Age, dtype: float64

## Fill with mean()

In [25]:
salary_mean=df['Salary'].mean()
df["Salary"]=df["Salary"].fillna(salary_mean)

In [26]:
df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   0.0  40000.0
2   Rohit  24.0  35000.0
3    Anil   0.0  35000.0

###  Fill with Median

In [30]:
age_mean=df['Age'].median()
df['Age']=df['Age'].fillna(age_mean)

In [31]:
df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   0.0  40000.0
2   Rohit  24.0  35000.0
3    Anil   0.0  35000.0

### Fill With Mode

For categorical data

In [36]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Rohit", None],
    "Age": [22, None, 24, None],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)

print(df)

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0      NaN
3    None   NaN  35000.0

In [37]:
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])

In [38]:
df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0      NaN
3  Harish   NaN  35000.0

### Forward filling

In [51]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Rohit", "Anil"],
    "Age": [22, None, 24, None],
    "Salary": [30000, 40000, None, 35000]
}

df = pd.DataFrame(data)

print(df)

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0      NaN
3    Anil   NaN  35000.0

In [52]:
df["Salary"] = df["Salary"].ffill()
df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul   NaN  40000.0
2   Rohit  24.0  40000.0
3    Anil   NaN  35000.0

### backward Fill

In [54]:
df["Age"] = df["Age"].bfill()
df

     Name   Age   Salary
0  Harish  22.0  30000.0
1   Rahul  24.0  40000.0
2   Rohit  24.0  40000.0
3    Anil   NaN  35000.0

# Duplicates

A duplicate means the same record appears more than once

In [87]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Rohit", "Harish"],
    "Age": [22, 21, 24, 22],
    "Salary": [30000, 40000, 20000, 30000]
}

df = pd.DataFrame(data)

df

     Name  Age  Salary
0  Harish   22   30000
1   Rahul   21   40000
2   Rohit   24   20000
3  Harish   22   30000

### find duplicates

-- Syntax:

        DataFrame.duplicated()

In [88]:
df.duplicated() # it gives boolean , True means duplicate row

0    False
1    False
2    False
3     True
dtype: bool

### Count of Duplicates

-- Syntax :

        DataFrame.duplicated().sum()

In [89]:
df.duplicated().sum()

np.int64(1)

### Display Duplicate Rows

In [90]:
df[df.duplicated()]

     Name  Age  Salary
3  Harish   22   30000

### Remove Duplicates Based on One Column

In [91]:
df.drop_duplicates(subset="Name")

     Name  Age  Salary
0  Harish   22   30000
1   Rahul   21   40000
2   Rohit   24   20000

### Remove Duplicates

Syntax :  

      DataFrame.drop_duplicates()

In [92]:
df.drop_duplicates()

     Name  Age  Salary
0  Harish   22   30000
1   Rahul   21   40000
2   Rohit   24   20000

### Keep Last Duplicate

In [94]:
df.drop_duplicates(
    subset=["Name"],
    keep="last"
)

     Name  Age  Salary
1   Rahul   21   40000
2   Rohit   24   20000
3  Harish   22   30000

### Remove All Copies of Duplicates

In [95]:
df.drop_duplicates(
    subset=['Name'],
    keep=False
)

    Name  Age  Salary
1  Rahul   21   40000
2  Rohit   24   20000