<a href="https://colab.research.google.com/github/HarishMayakuntla/Data-science-pandas-practice/blob/main/pd_R_W_csv_excel_json.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas Reading/Writing CSV, Excel, JSON

## CSV File (comma separeted value)

In [ ]:
 ## this is google colab so i can choose the select file
 # why because it is not direct access to the local disc
from google.colab import files
uploaded=files.upload()

Saving student.csv to student.csv

## Read CSV

In [ ]:
import pandas as pd

df = pd.read_csv('student.csv')

df

    ID  Age  Math  Science  English
0    1   18    85       90       88
1    2   19    78       82       80
2    3   20    92       95       91
3    4   18    88       84       86
4    5   19    75       79       77
5    6   20    81       85       83
6    7   21    90       92       89
7    8   18    67       70       72
8    9   19    95       96       94
9   10   20    73       75       74
10  11   21    84       86       85
11  12   18    79       81       80
12  13   19    91       93       92
13  14   20    69       72       70
14  15   21    87       89       88
15  16   18    76       78       79
16  17   19    82       84       83
17  18   20    94       97       95
18  19   21    71       73       72
19  20   18    89       91       90
20  21   19    80       83       81
21  22   20    77       79       78
22  23   21    93       95       94
23  24   18    68       71       69
24  25   19    86       88       87
25  26   20    74       76       75
26  27   21    90       91       92
27  28   18    83       85       84
28  29   19    96       98       97
29  30   20    72       74       73
30  31   21    88       90       89
31  32   18    79       80       81
32  33   19    85       87       86
33  34   20    70       72       71
34  35   21    92       94       93
35  36   18    81       82       83
36  37   19    76       78       77
37  38   20    95       97       96
38  39   21    73       75       74
39  40   18    87       89       88
40  41   19    84       86       85
41  42   20    69       71       70
42  43   21    91       93       92
43  44   18    78       80       79
44  45   19    82       83       84
45  46   20    97       99       98
46  47   21    75       77       76
47  48   18    89       90       91
48  49   19    80       82       81
49  50   20    93       95       94

## check the data

In [ ]:
df.head()

   ID  Age  Math  Science  English
0   1   18    85       90       88
1   2   19    78       82       80
2   3   20    92       95       91
3   4   18    88       84       86
4   5   19    75       79       77

In [ ]:
df.tail()

    ID  Age  Math  Science  English
45  46   20    97       99       98
46  47   21    75       77       76
47  48   18    89       90       91
48  49   19    80       82       81
49  50   20    93       95       94

In [ ]:
df.shape

(50, 5)

In [ ]:
df.columns

Index(['ID', 'Age', 'Math', 'Science', 'English'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID       50 non-null     int64
 1   Age      50 non-null     int64
 2   Math     50 non-null     int64
 3   Science  50 non-null     int64
 4   English  50 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB

## write DataFrame to CSV

In [ ]:
## create a new CSV file

df.to_csv("new_students.csv")

In [ ]:
## here If you don't want the Pandas index
df.to_csv('new_students.csv',index=False)

In [ ]:
df

    ID  Age  Math  Science  English
0    1   18    85       90       88
1    2   19    78       82       80
2    3   20    92       95       91
3    4   18    88       84       86
4    5   19    75       79       77
5    6   20    81       85       83
6    7   21    90       92       89
7    8   18    67       70       72
8    9   19    95       96       94
9   10   20    73       75       74
10  11   21    84       86       85
11  12   18    79       81       80
12  13   19    91       93       92
13  14   20    69       72       70
14  15   21    87       89       88
15  16   18    76       78       79
16  17   19    82       84       83
17  18   20    94       97       95
18  19   21    71       73       72
19  20   18    89       91       90
20  21   19    80       83       81
21  22   20    77       79       78
22  23   21    93       95       94
23  24   18    68       71       69
24  25   19    86       88       87
25  26   20    74       76       75
26  27   21    90       91       92
27  28   18    83       85       84
28  29   19    96       98       97
29  30   20    72       74       73
30  31   21    88       90       89
31  32   18    79       80       81
32  33   19    85       87       86
33  34   20    70       72       71
34  35   21    92       94       93
35  36   18    81       82       83
36  37   19    76       78       77
37  38   20    95       97       96
38  39   21    73       75       74
39  40   18    87       89       88
40  41   19    84       86       85
41  42   20    69       71       70
42  43   21    91       93       92
43  44   18    78       80       79
44  45   19    82       83       84
45  46   20    97       99       98
46  47   21    75       77       76
47  48   18    89       90       91
48  49   19    80       82       81
49  50   20    93       95       94

# excel files

Excel files normally have .xlsx extension

## read excel file

In [ ]:
##  we need install the openpyxl  library

! pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
uploaded=files.upload()

Saving students.xlsx to students.xlsx

In [ ]:

df=pd.read_excel('students.xlsx')

df

    ID  Age  Math  Science  English
0    1   18    85       90       88
1    2   19    78       82       80
2    3   20    92       95       91
3    4   18    88       84       86
4    5   19    75       79       77
5    6   20    81       85       83
6    7   21    90       92       89
7    8   18    67       70       72
8    9   19    95       96       94
9   10   20    73       75       74
10  11   21    84       86       85
11  12   18    79       81       80
12  13   19    91       93       92
13  14   20    69       72       70
14  15   21    87       89       88
15  16   18    76       78       79
16  17   19    82       84       83
17  18   20    94       97       95
18  19   21    71       73       72
19  20   18    89       91       90
20  21   19    80       83       81
21  22   20    77       79       78
22  23   21    93       95       94
23  24   18    68       71       69
24  25   19    86       88       87
25  26   20    74       76       75
26  27   21    90       91       92
27  28   18    83       85       84
28  29   19    96       98       97
29  30   20    72       74       73
30  31   21    88       90       89
31  32   18    79       80       81
32  33   19    85       87       86
33  34   20    70       72       71
34  35   21    92       94       93
35  36   18    81       82       83
36  37   19    76       78       77
37  38   20    95       97       96
38  39   21    73       75       74
39  40   18    87       89       88
40  41   19    84       86       85
41  42   20    69       71       70
42  43   21    91       93       92
43  44   18    78       80       79
44  45   19    82       83       84
45  46   20    97       99       98
46  47   21    75       77       76
47  48   18    89       90       91
48  49   19    80       82       81
49  50   20    93       95       94

## Reading a particular sheet

Suppose the Excel file contains:

* Sheet1
* Students
* Marks

In [ ]:
df = pd.read_excel("students.xlsx", sheet_name="student")

df

    ID  Age  Math  Science  English
0    1   18    85       90       88
1    2   19    78       82       80
2    3   20    92       95       91
3    4   18    88       84       86
4    5   19    75       79       77
5    6   20    81       85       83
6    7   21    90       92       89
7    8   18    67       70       72
8    9   19    95       96       94
9   10   20    73       75       74
10  11   21    84       86       85
11  12   18    79       81       80
12  13   19    91       93       92
13  14   20    69       72       70
14  15   21    87       89       88
15  16   18    76       78       79
16  17   19    82       84       83
17  18   20    94       97       95
18  19   21    71       73       72
19  20   18    89       91       90
20  21   19    80       83       81
21  22   20    77       79       78
22  23   21    93       95       94
23  24   18    68       71       69
24  25   19    86       88       87
25  26   20    74       76       75
26  27   21    90       91       92
27  28   18    83       85       84
28  29   19    96       98       97
29  30   20    72       74       73
30  31   21    88       90       89
31  32   18    79       80       81
32  33   19    85       87       86
33  34   20    70       72       71
34  35   21    92       94       93
35  36   18    81       82       83
36  37   19    76       78       77
37  38   20    95       97       96
38  39   21    73       75       74
39  40   18    87       89       88
40  41   19    84       86       85
41  42   20    69       71       70
42  43   21    91       93       92
43  44   18    78       80       79
44  45   19    82       83       84
45  46   20    97       99       98
46  47   21    75       77       76
47  48   18    89       90       91
48  49   19    80       82       81
49  50   20    93       95       94

## Read all sheets

In [ ]:
data = pd.read_excel("students.xlsx", sheet_name=None)

data

{'student':     ID  Age  Math  Science  English
 0    1   18    85       90       88
 1    2   19    78       82       80
 2    3   20    92       95       91
 3    4   18    88       84       86
 4    5   19    75       79       77
 5    6   20    81       85       83
 6    7   21    90       92       89
 7    8   18    67       70       72
 8    9   19    95       96       94
 9   10   20    73       75       74
 10  11   21    84       86       85
 11  12   18    79       81       80
 12  13   19    91       93       92
 13  14   20    69       72       70
 14  15   21    87       89       88
 15  16   18    76       78       79
 16  17   19    82       84       83
 17  18   20    94       97       95
 18  19   21    71       73       72
 19  20   18    89       91       90
 20  21   19    80       83       81
 21  22   20    77       79       78
 22  23   21    93       95       94
 23  24   18    68       71       69
 24  25   19    86       88       87
 25  26   20    74       76       75
 26  27   21    90       91       92
 27  28   18    83       85       84
 28  29   19    96       98       97
 29  30   20    72       74       73
 30  31   21    88       90       89
 31  32   18    79       80       81
 32  33   19    85       87       86
 33  34   20    70       72       71
 34  35   21    92       94       93
 35  36   18    81       82       83
 36  37   19    76       78       77
 37  38   20    95       97       96
 38  39   21    73       75       74
 39  40   18    87       89       88
 40  41   19    84       86       85
 41  42   20    69       71       70
 42  43   21    91       93       92
 43  44   18    78       80       79
 44  45   19    82       83       84
 45  46   20    97       99       98
 46  47   21    75       77       76
 47  48   18    89       90       91
 48  49   19    80       82       81
 49  50   20    93       95       94}

## Write to excel

In [ ]:
df.to_excel("new_students.xlsx", index=False)
df

    ID  Age  Math  Science  English
0    1   18    85       90       88
1    2   19    78       82       80
2    3   20    92       95       91
3    4   18    88       84       86
4    5   19    75       79       77
5    6   20    81       85       83
6    7   21    90       92       89
7    8   18    67       70       72
8    9   19    95       96       94
9   10   20    73       75       74
10  11   21    84       86       85
11  12   18    79       81       80
12  13   19    91       93       92
13  14   20    69       72       70
14  15   21    87       89       88
15  16   18    76       78       79
16  17   19    82       84       83
17  18   20    94       97       95
18  19   21    71       73       72
19  20   18    89       91       90
20  21   19    80       83       81
21  22   20    77       79       78
22  23   21    93       95       94
23  24   18    68       71       69
24  25   19    86       88       87
25  26   20    74       76       75
26  27   21    90       91       92
27  28   18    83       85       84
28  29   19    96       98       97
29  30   20    72       74       73
30  31   21    88       90       89
31  32   18    79       80       81
32  33   19    85       87       86
33  34   20    70       72       71
34  35   21    92       94       93
35  36   18    81       82       83
36  37   19    76       78       77
37  38   20    95       97       96
38  39   21    73       75       74
39  40   18    87       89       88
40  41   19    84       86       85
41  42   20    69       71       70
42  43   21    91       93       92
43  44   18    78       80       79
44  45   19    82       83       84
45  46   20    97       99       98
46  47   21    75       77       76
47  48   18    89       90       91
48  49   19    80       82       81
49  50   20    93       95       94

# json files

JSON means JavaScript Object Notation

In [ ]:
uploaded=files.upload()

Saving student.json to student.json

In [ ]:
df=pd.read_json('student.json')

df

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78

In [ ]:
df.to_json('new_student.json')

df

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78

In [ ]:
## for cleaner format
df.to_json('new_student.json',orient='records',indent=4)
df

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78

## Real Example

In [ ]:
import pandas as pd

data = {
    "Name": ["Harish", "Rahul", "Ravi"],
    "Age": [22, 21, 23],
    "Marks": [85, 78, 92]
}

dframe = pd.DataFrame(data)

dframe

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78
2    Ravi   23     92

In [ ]:
dframe.to_csv("student.csv",index=False)

In [ ]:
dframe

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78
2    Ravi   23     92

In [ ]:
dframe.to_excel("students.xlsx", index=False)

In [ ]:
dframe

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78
2    Ravi   23     92

In [ ]:
dframe.to_json("students.json", orient="records", indent=4)

In [ ]:
dframe

     Name  Age  Marks
0  Harish   22     85
1   Rahul   21     78
2    Ravi   23     92

In [ ]:
dframe.describe()

        Age  Marks
count   3.0    3.0
mean   22.0   85.0
std     1.0    7.0
min    21.0   78.0
25%    21.5   81.5
50%    22.0   85.0
75%    22.5   88.5
max    23.0   92.0